"""create camera model

Revision ID: 67962fd63d63
Revises:
Create Date: 2025-05-26 14:59:13.687183

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67962fd63d63"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "d_camera",
        sa.Column("id", sa.UUID(), nullable=False, comment="Идентификатор камеры"),
        sa.Column("camera_id", sa.String(), nullable=True, comment="Номер камеры"),
        sa.Column(
            "camera_class_cd",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор класса камеры",
        ),
        sa.Column("camera_class", sa.String(), nullable=True, comment="Класс камеры"),
        sa.Column("model", sa.String(), nullable=True, comment="Модель"),
        sa.Column(
            "camera_name",
            sa.String(),
            nullable=True,
            comment="Название камеры",
        ),
        sa.Column("camera_place", sa.String(), nullable=True, comment="Адрес"),
        sa.Column(
            "camera_place_cd",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор адреса",
        ),
        sa.Column(
            "serial_number",
            sa.String(),
            nullable=True,
            comment="Серийный номер",
        ),
        sa.Column(
            "camera_type_cd",
            sa.Integer(),
            nullable=True,
            comment="Идентификатор типа камеры",
        ),
        sa.Column("camera_type", sa.String(), nullable=True, comment="Тип камеры"),
        sa.Column("camera_latitude", sa.Float(), nullable=True, comment="Широта"),
        sa.Column("camera_longitude", sa.Float(), nullable=True, comment="Долгота"),
        sa.Column(
            "archive",
            sa.Integer(),
            nullable=True,
            comment="Признак архивной записи",
        ),
        sa.Column("azimuth", sa.Integer(), nullable=True, comment="Азимут"),
        sa.Column(
            "process_dttm",
            sa.DateTime(),
            nullable=True,
            comment="Дата и время добавления записи в таблицу (техн.)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("d_camera")
    # ### end Alembic commands ###
