"""updated models

Revision ID: 0ce9374b0944
Revises: 6d9e2c4e086d
Create Date: 2025-05-28 17:57:04.911003

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ce9374b0944"
down_revision: str | None = "6d9e2c4e086d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video",
        sa.Column(
            "data_created",
            sa.DateTime(),
            nullable=False,
            comment="Дата создания",
        ),
    )
    op.add_column(
        "video",
        sa.Column(
            "author_id",
            sa.UUID(),
            nullable=False,
            comment="Идентификатор автора",
        ),
    )
    op.create_foreign_key(None, "video", "user", ["author_id"], ["id"])
    op.drop_column("video", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video",
        sa.Column(
            "author",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Автор",
        ),
    )
    op.drop_constraint(None, "video", type_="foreignkey")
    op.drop_column("video", "author_id")
    op.drop_column("video", "data_created")
    # ### end Alembic commands ###
