"""user and camera models add

Revision ID: 700a3d64ed7d
Revises: bc0ea6654ace
Create Date: 2025-05-27 18:52:48.594326

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "700a3d64ed7d"
down_revision: str | None = "bc0ea6654ace"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_user_user_email"), "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_user_email"), "user", type_="unique")
    # ### end Alembic commands ###
