"""updated constraint

Revision ID: bf96ceef1fbe
Revises: 0aa04e52dfc5
Create Date: 2025-05-29 17:57:58.213764

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bf96ceef1fbe"
down_revision: str | None = "0aa04e52dfc5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
