"""updated constraint

Revision ID: 751188055666
Revises: bf96ceef1fbe
Create Date: 2025-05-29 18:05:13.737549

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "751188055666"
down_revision: str | None = "bf96ceef1fbe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video",
        sa.Column("author_name", sa.String(), nullable=False, comment="Автор"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "author_name")
    # ### end Alembic commands ###
